### ISSUE TITLE
公式6与图12

### ISSUE THREAD

**Issue by czzbb** [Algolzw/image-restoration-sde#100]
您好，根据图12，theta_t的累乘应该等于1？那么公式6中，当t->∞时，m_t(x)=μ-(x(0)-μ)/e。并不会等于μ？

**Comment by Algolzw** [comment]
你好，图12并不是theta_t的累积，而公式6中\bat{\theta}_t表示的是所有theta的累加，其数值可以参考appendix D中倒数第二行的内容哈。

**Comment by czzbb** [comment]
> 你好，图12并不是theta_t的累积，而公式6中\bat{\theta}_t表示的是所有theta的累加，其数值可以参考appendix D中倒数第二行的内容哈。

明白了感谢。还想请教一下 dt 为什么是这样定义的，https://github.com/Algolzw/image-restoration-sde/blob/2598d73cde3a1e2cf78c4ba4923414e1f4b90393/codes/utils/sde_utils.py#L143
