### ISSUE TITLE
inpainting任务中的celebA数据集

### ISSUE THREAD

**Issue by Frank-Cai0709** [Algolzw/image-restoration-sde#102]
作者您好，inpainting任务中的celebAHQ 256数据集,是按照什么比例划分的训练集和测试集呢？（或者是基于哪篇paper的划分方式呢），找到的celebAHQ 256数据集都是完整的30000张图，未做训练集测试集的划分。

**Comment by Algolzw** [comment]
你好我是把前100个作为validation data，具体训练数据可以在[这里](https://drive.google.com/file/d/1oYDBcJLT5RDuC4k5C7xOMRkZ9N3kfexu/view?usp=drive_link)下载。而验证集只有个DA-CLIP的[链接](https://drive.google.com/file/d/1JKd1tA7rMoEbI9190daJqL7i6V1L8KUd/view?usp=drive_link)（10个数据集），你可以在里面找到inpainting的验证集。
