### ISSUE TITLE
超分任务的训练集，验证集及评估数据集的选择

### ISSUE THREAD

**Issue by Frank-Cai0709** [Algolzw/image-restoration-sde#105]
作者您好！

论文里提到超分任务使用了div2k数据集。结合yml文件，想请教作者，数据集是否如以下选择：训练集使用了div2k的800张训练图像，验证val使用的是set5的5张图像，评估指标（evaluaiton）使用的是div2k的验证集中100张图像（801-900）？

 期待您的回复。

<img width="470" alt="image" src="https://github.com/user-attachments/assets/3a4b93f1-0a97-473d-bc6d-084d8a64cfb8">

**Comment by Algolzw** [comment]
你好，是这样的。不过我们还预先把LR resize到和HR一样的大小。

**Comment by Frank-Cai0709** [comment]
好的，谢谢您的解答。
