### ISSUE TITLE
关于到某一iter显存爆炸的问题

### ISSUE THREAD

**Issue by SueZhang2000** [Algolzw/image-restoration-sde#107]
作者您好！想询问一下跑到11200iter时程序会卡死的情况是什么原因呢？已经连续两次出现这种情况了，是训练集输入图像尺寸过大的原因吗？若能回复不胜感激！祝学长多中paper科研顺利！
![image](https://github.com/user-attachments/assets/a192298d-f4b2-483a-92d8-e4f8356acabf)

**Comment by Algolzw** [comment]
你可以查看一下显存和内存使用情况呢？如果是内存使用过大，可以尝试使用更小的patch size以及把dataloader中的pin_memory设为False。

**Comment by SueZhang2000** [comment]
您好！是系统内存的问题，已解决，非常感谢！

**Comment by SueZhang2000** [comment]
作者您好，程序基本不占用显存，但是内存会随着迭代次数的增多而增加直至爆炸，请问如何改善这个问题呢？非常感谢！
