### ISSUE TITLE
代码问题：reverse_posterior?

### ISSUE THREAD

**Issue by zjYao36** [Algolzw/image-restoration-sde#110]
您好！请问使用reverse_posterior时reverse_optimum_std是如何计算的呢，我在文中似乎没有找到对应？https://github.com/Algolzw/image-restoration-sde/blob/2598d73cde3a1e2cf78c4ba4923414e1f4b90393/codes/utils/sde_utils.py#L207C5-L217C64

**Comment by Algolzw** [comment]
你好，posterior sampling是我们后来在这篇[Photo-Realistic Image Restoration in the Wild with Controlled Vision-Language Models](https://arxiv.org/abs/2404.09732)论文中提出专门适配IR-SDE的方法哈。

**Comment by zjYao36** [comment]
好的，非常感谢您！
