### ISSUE TITLE
shadow removal dataset

### ISSUE THREAD

**Issue by ruffiann** [Algolzw/image-restoration-sde#12]
very nice work! i'm sorry to bother you, but i can't find the dataset you used in shadow removal task according to the references in your paper. could you please give me a link or other information about it? thanks very much

**Comment by Algolzw** [comment]
Hi,

All datasets used in Refusion paper can find through this [NTIRE 2023 page](https://cvlai.net/ntire/2023/). 

For image shadow removal, here are the download links (from [CodaLab](https://codalab.lisn.upsaclay.fr/competitions/10253)):
[train(LQ)](https://codalab.lisn.upsaclay.fr/my/datasets/download/99306bb4-833b-4971-b27f-22e244eac074), [train(HQ)](https://codalab.lisn.upsaclay.fr/my/datasets/download/ddcf4107-eed2-4c49-9cf5-fb6a2998d466), [validation LQ](https://codalab.lisn.upsaclay.fr/my/datasets/download/d284be60-a575-4a99-a683-0efa60325ce4), [test(LQ)](https://codalab.lisn.upsaclay.fr/my/datasets/download/8e13eb94-85a1-4c0f-ba8d-38154157e030).

The official dataset version might be released a few months later. You can also wait until that time to download the official version.

**Comment by ruffiann** [comment]
thank you very much!
