### ISSUE TITLE
torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by poxiao0** [Algolzw/image-restoration-sde#13]
Thank you for your fantastic work.
I have only a 3060, I set the batchsize 2, but happens OutOfMemoryError at 5000 iters, where can I modify the code to run?

**Comment by Algolzw** [comment]
Hi! Which model are you training, and what size are your test images? From my experience, you can set smaller patch-size or fewer channels to save the training memory.

**Comment by poxiao0** [comment]
> Hi! Which model are you training, and what size are your test images? From my experience, you can set smaller patch-size or fewer channels to save the training memory.

My training model is IR-SDE for SISR, my dataset is DIV2K, the size is 32*32->128*128, my 3036 has 11G memory

**Comment by poxiao0** [comment]
I try, set size 16 × 16 -> 64 × 64 and network_G.setting.nf = 32, it also stop at 5000 iters, maybe the cpmputation limit is huge.

**Comment by poxiao0** [comment]
> Hi! Which model are you training, and what size are your test images? From my experience, you can set smaller patch-size or fewer channels to save the training memory.

I try, set size 16 × 16 -> 64 × 64 (original is 32 × 32 -> 128 × 128）and network_G.setting.nf = 32(original is 64), it also stop at 5000 iters, maybe the computation limit is huge.

**Comment by poxiao0** [comment]
> Hi! Which model are you training, and what size are your test images? From my experience, you can set smaller patch-size or fewer channels to save the training memory.

I try again with two 3060 and also happen the OutOfMemory at 5000 iters, the model and size is same as above.Maybe I need more computation device.

**Comment by Algolzw** [comment]
Hi, since our work upsamples the LR image to have the same size as the HR image, it needs more memory than standard SR approaches. However, you can only evaluate the center-cropped images (256x256) like other diffusion models (such as SRDiff), which should work even on one 12G GPU.

**Comment by poxiao0** [comment]
> Hi, since our work upsamples the LR image to have the same size as the HR image, it needs more memory than standard SR approaches. However, you can only evaluate the center-cropped images (256x256) like other diffusion models (such as SRDiff), which should work even on one 12G GPU.

Now,I can run it on one 3060,thank you for your work, code and advice,it takes me half a week.I once learned SDE a little in diffusion model and occurly found your work, I was excited.Hope you will accept more good work like CVPR、ICCV or ECCV so on!

**Comment by Algolzw** [comment]
Thank you! Hope you all the best as well!
