### ISSUE TITLE
About “latent-replacing training strategy”

### ISSUE THREAD

**Issue by hello2377** [Algolzw/image-restoration-sde#26]
How is latent-dehazing.pth obtained ? HQ--->HQ reconstruction ？

**Comment by Algolzw** [comment]
It is trained by the U-Net in the [unet-latent](https://github.com/Algolzw/image-restoration-sde/tree/main/codes/config/unet-latent) dir. You can modify the data dir to retrain the U-Net model and save it as the latent-dehazing.pth.
