### ISSUE TITLE
Pre-trained weights for inpainting

### ISSUE THREAD

**Issue by azlanqazi2012** [Algolzw/image-restoration-sde#30]
Hi,

Can you please share pre-trained weights for inpainting?

**Comment by Algolzw** [comment]
Hi,

All results and pretrained weights can be found in [here](https://drive.google.com/drive/folders/14SvJXvp0HPKFHpGaaHy7h2I2fkRnIXAG?usp=sharing).

**Comment by azlanqazi2012** [comment]
Thanks
