### ISSUE TITLE
就Deraining在训练和测试时分别输送到网络的shape区别向学长请教！

### ISSUE THREAD

**Issue by Haozhouhao** [Algolzw/image-restoration-sde#32]
罗学长，你好，我注意到在训练的过程中，若配置文件指定参数GT_size: 128 则输送到网络前，图像会进行裁剪（128）等数据增强，而后在unet中再进行适当的padding；而在测试过程中，若直接使用您分享的checkpoint以及相应的测试yml文件，除了在unet中有相应的padding，是不需要对图像做相应操作的，如测试集中的单张图像shape为[1,3,321,481],
我的问题是，训练过程中输送给unet的shape是[b,c,128,128] 测试时输送给unet的shape是[b,c,336,496]  (根据默认的yml文件计算)？ 所以，unet 所保存的权重仅仅是那些卷积核权重等，不会受到输入的shape的变化所影响，而只受到通道变化的影响？不知道我这样理解的对不对？
如果是这样的话，我的疑问便是，resolution的变化会不会对扩散模型学习的分布有所影响呢？

**Comment by Algolzw** [comment]
是的哈，这里的输入理论上可以有任何shape。分辨率肯定是会有影响的，毕竟如果有一大片区域是0值的话也会影响整个生成效果。不过目前除了padding外还没有有效的方式来处理任意形状图像，个人觉得这应该也是一个值得探索的方向。

**Comment by Haozhouhao** [comment]
非常感谢学长的耐心解答，学长能简要说明下有关超分的sisr和stereo-sr的区别吗？再次感谢

**Comment by Algolzw** [comment]
好的。stereo-sr也就是双目超分，即同时输入左右两张LR图像，其大部分区域相似但视角不一样。与sisr相比，stereo-sr的左右视角图像可以相互作为辅助图像来加强超分效果，理论上是要比单图超分好一些的。具体的你可以搜一下今年比赛的[report](https://openaccess.thecvf.com/content/CVPR2023W/NTIRE/html/Wang_NTIRE_2023_Challenge_on_Stereo_Image_Super-Resolution_Methods_and_Results_CVPRW_2023_paper.html)来看一下。
