### ISSUE TITLE
去除路面上的阴影没效果

### ISSUE THREAD

**Issue by DepapepeOne** [Algolzw/image-restoration-sde#41]
大佬您好，我在使用您的去阴影的模型去除您论文中的阴影图片的效果挺好的，但是去除我们这边应用场景中的图片感觉没啥效果，下面是我们使用场景的图片以及使用这个算法去除阴影后的效果
包含阴影的图片
![1](https://github.com/Algolzw/image-restoration-sde/assets/12411159/035d5625-7086-43d6-847c-7d58e068a39d)
使用该算法去除阴影后的图片
![1](https://github.com/Algolzw/image-restoration-sde/assets/12411159/eadb89b9-024f-4466-a4f4-ba0e61365d1f)

请问下这个算法能去除户外路面上的阴影吗

**Comment by Algolzw** [comment]
你好，可能是数据集差异比较大导致效果不好。我们提供的模型是在室内灯光阴影数据集(NTIRE 2023 deshadow challenge)上训练的，如果你想去除户外路面阴影的话可能还需要对应的数据集重新训练。

**Comment by DepapepeOne** [comment]
好的，明白了，谢谢您
