### ISSUE TITLE
关于unet-latent代码的测试问题

### ISSUE THREAD

**Issue by xiaojiebangbang** [Algolzw/image-restoration-sde#54]
作者您好，请问unet-latent这套代码中（不是latent-dehazing这套代码），我在测试时用的是一张图片，model.test（）会进入到latent-model里面的test，这里没有GT图像也就得不到它的hidden和latent，请问这样该怎么测试呢，耐心等待您的解答！

**Comment by xiaojiebangbang** [comment]
还是说unet-latent这套代码训练的unet网络是为latent-dehazing服务的，我的目标是想做图像去噪，单张图片去噪的话是要用latent-dehazing这个代码嘛？求指点。

**Comment by Algolzw** [comment]
你好，unet-latent这个模型只是第一个阶段类似于latent-diffusion中的VAE。你要降噪的话确实还需要训练一个denoising模型(使用latent-dehazing代码)作为Stage 2哈。

**Comment by xiaojiebangbang** [comment]
感谢您如此快速的回复，对我帮助很大，祝生活愉快！

**Comment by xiaojiebangbang** [comment]
请问lr-steps这个参数有什么作用？

**Comment by Algolzw** [comment]
这个参数是哪儿的啊？

**Comment by xiaojiebangbang** [comment]
在训练opyions参数文件中的优化器部分

**Comment by Algolzw** [comment]
哦哦这个是当 lr_scheme设置为MultiStepLR时学习率下降的milestones，可以参考[pytorch官网](https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.MultiStepLR.html)。

**Comment by xiaojiebangbang** [comment]
好的好的，谢谢您



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: balabala ***@***.***&gt;
发送时间: 2023年10月27日 22:05
收件人: Algolzw/image-restoration-sde ***@***.***&gt;
抄送: xiaojiebangbang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Algolzw/image-restoration-sde] 关于unet-latent代码的测试问题 (Issue #54)





 
哦哦这个是当 lr_scheme设置为MultiStepLR时学习率下降的milestones，可以参考pytorch官网。
