### ISSUE TITLE
作者您好！代码问题想请教

### ISSUE THREAD

**Issue by MrWan001** [Algolzw/image-restoration-sde#59]
![image](https://github.com/Algolzw/image-restoration-sde/assets/126931904/15553d50-d70c-40bc-8fcd-495765128a51)
在DenoisingUNet和DenoisingNAFNet的代码中，我理解的输入是Xt和cond拼接，Xt是时刻t的状态，cond是低质图像作为条件，两个3通道拼接好之后是6通道，但是我看代码中是X=Xt-cond，然后X和cond拼接，不太明白Xt-cond是什么操作，我理解的Xt和cond有问题吗
期待您的回复！

**Comment by Algolzw** [comment]
这是因为在公式中算score时有个 $x_t - \mu_t$项，其中\mu_t含有cond项，即score计算时有$x_t - cond$项。所以我在代码中使用$x_t - cond$代替x_t期望使预测更加容易。

**Comment by MrWan001** [comment]
好的，明白了，谢谢
