### ISSUE TITLE
关于图像尺寸的问题

### ISSUE THREAD

**Issue by MrWan001** [Algolzw/image-restoration-sde#61]
作者您好，配置文件里显示的图像尺寸 GT_size: 128和 LR_size: 128，也就是说去噪网络UNet或者NAFNet处理的是128大小的图像，但是在测试时得到的result是输入图像的原尺寸，我想请问得到的result的尺寸是怎么恢复回来的，是用resize函数吗。

我阅读了您之前的回答，在latent模型中，可以通过预训练的U-Net让图像尺寸恢复回来，但在非latent模型，比如去雨任务的代码中，图像尺寸是如何恢复回原来大小的

期待您的回复

**Comment by Algolzw** [comment]
你好，对于不规则图像我们是使用补边的操作对图像先进行padding再在输出上进行裁剪得到和原图一样的尺寸：如[这里](https://github.com/Algolzw/image-restoration-sde/blob/74b6608b02972e0adf986affb974e14511193f28/codes/config/deraining/models/modules/DenoisingNAFNet_arch.py#L183)。注意配置文件中的128指的是training过程，而测试的话是可以任意尺寸。

**Comment by MrWan001** [comment]
好的，感谢您的耐心回复
