### ISSUE TITLE
refusion for inpainting task

### ISSUE THREAD

**Issue by luwang03** [Algolzw/image-restoration-sde#70]
Hi. How can i train the refusion model for inpainting task? what should i do to train it?

**Comment by Algolzw** [comment]
Hi. You may need to retrain a [latent-unet](https://github.com/Algolzw/image-restoration-sde/tree/74b6608b02972e0adf986affb974e14511193f28/codes/config/unet-latent) model for the inpainting dataset and then change the path (including datasets and pretrained unet weight) in [latent-dehazing](https://github.com/Algolzw/image-restoration-sde/tree/74b6608b02972e0adf986affb974e14511193f28/codes/config/latent-dehazing) for inpainting.

**Comment by luwang03** [comment]
OK. Thank you very much!
