### ISSUE TITLE
can't compute flops using torchsummaryX

### ISSUE THREAD

**Issue by luwang03** [Algolzw/image-restoration-sde#72]
When I computed the flops  of model, the code as:

![image](https://github.com/Algolzw/image-restoration-sde/assets/26894064/052c7734-1025-4303-b042-a574e524795b)

, I met an error as:
![image](https://github.com/Algolzw/image-restoration-sde/assets/26894064/08c6e6d9-91fd-4f72-9d8f-93ef2391ecec)

How can I solve this problem?

**Comment by Algolzw** [comment]
The code seems correct and I didn't meet this problem. Did you change something in the denoising network?

**Comment by luwang03** [comment]
I changed nothing in the denoising network.

**Comment by Algolzw** [comment]
Maybe it's the version problem. Can you upgrade your torchsummaryX to 1.3.0?

**Comment by luwang03** [comment]
Actually, my torchsummaryX is1.3.0.

**Comment by luwang03** [comment]
For thehe error in 
![image](https://github.com/Algolzw/image-restoration-sde/assets/26894064/5a65d12a-bfd3-4eb7-ba71-24d976044dde),
I printed the 'a' is
![image](https://github.com/Algolzw/image-restoration-sde/assets/26894064/f6cd372d-e25c-4e1c-ba21-d8353c74516f)

**Comment by luwang03** [comment]
It seems the 'a' array has '-' entry.

**Comment by Algolzw** [comment]
= =.

It's really weird because the code works very well for me.
![Screenshot 2023-12-19 at 10 43 06](https://github.com/Algolzw/image-restoration-sde/assets/15884127/1121f5e6-ec14-48df-8d6d-0029be1fd1b5)

Maybe it doesn't work on Windows?

**Comment by luwang03** [comment]
Maybe you are right! Windows can't work it.

**Comment by Algolzw** [comment]
Yes. Or can you try to add the `__init__` function to SimpleGate and add `super().__init__()` to it as well?

**Comment by luwang03** [comment]
Sorry for my late reply. I tried __init__ function, Windows also can't work. Maybe I need to run the codes on linux. Thanks for your help.
