### ISSUE TITLE
去雾后图像输出结果为紫色

### ISSUE THREAD

**Issue by ZHB2333** [Algolzw/image-restoration-sde#89]
你好，我使用latent-dehazing模块进行去雾后，图像输出结果不正常，我不知道如何解决该问题，所使用的参数是-opt=options/dehazing/test/nasde.yml，使用了latent-dehazing.pth与latent-reffusion-dehazing.pth，输入与输出结果[在这](https://drive.google.com/drive/folders/1PjKrtOxnxpU999Niqmxu-z0zHsdDb5zS?usp=drive_link)
期待你的回复。

**Comment by Algolzw** [comment]
你好，这个问题还存在吗？你可以尝试一下只使用latent-dehazing对图像进行reconstruction看看知否是正确的权重。

**Comment by ZHB2333** [comment]
你好，目前还没解决这个问题，只使用latent-dehazing是指只使用latent-dehazing.pth预训练模型么，我是分别使用的两种预训练模型的进行测试的，其次我用相同方法测试了deraining和deshadow模块，测试效果都很好，只有latent-dehazing模块测试后图像输出结果不正常，没有找出是什么原因。期待你的回复！

**Comment by Algolzw** [comment]
我是发现你提供的[latent结果](https://drive.google.com/file/d/1tOmIDm3dhNf6WOpT-1GoajPL6i2B-Gf8/view?usp=drive_link)好像有点奇怪。可以尝试在latent中跳过diffusion这一步呢，看看能不能直接恢复原图（用于判断latent dehazing模型是否有问题）。

**Comment by ZHB2333** [comment]
按照你的思路终于解决了这个问题！我发现latent-reffusion-dehazing.pth和latent-dehazing.pth两个预训练模型原来需要一起使用，我之前是单独只使用一个进行测试的，两个模型一起使用后恢复正常了，这不同于deraining模块只需用一个预训练模型
